services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    ports:
      - 6333:6333 # tcp
      - 6334:6334 # grpc
    expose:
      - 6333
      - 6334
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always

  website:
    image: document_search
    build:
      context: .
      dockerfile: Dockerfile
    user: 'node'
    environment:
      - TZ=US/Pacific
      - QDRANT_HOST=qdrantdb
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 4173:4173

volumes:
  qdrant_data:

